Fix About screen being empty in release build
Error message in logcat:

> java.lang.IllegalStateException: Please provide the required library data via the available APIs.
> Depending on the platform this can be done for example via `Libs.Builder().withJson()`.
> For Android there exists an `Libs.Builder().withContext(context).build()`, automatically loading the `aboutlibraries.json` file from the `raw` resources folder.

The underlying cause was the upgrade to AGP 9 and its changes to resources shrinking.

See also:

- https://gitlab.com/fmd-foss/fmd-android/-/merge_requests/500
- https://github.com/mikepenz/AboutLibraries/issues/1296
- https://github.com/mikepenz/AboutLibraries#optimized-resource-shrinking--agp-90